### ISSUE TITLE
Default action in Filter

### ISSUE THREAD

**Issue by rpalcolea** [erickmorales3/action-logging#5]
Hi @erickmorales3 

I'm opening a few issues, hope that's ok.

https://github.com/erickmorales3/action-logging/blob/master/grails-app/conf/ActionLoggingFilters.groovy#L50

```
 if (!actionName) {
                        actionNameValue = "index"
                    }
```

Perhaps reading the `static defaultAction` first and then fallback to `index` would be better

**Comment by burtbeckwith** [comment]
I think the most reliable source for the name of the default action is from the GrailsControllerClass e.g. `grailsApplication.getControllerClass(classname).defaultAction`

**Comment by erickmorales3** [comment]
I solved using defaultAction if is present and if is not, it's finding controller action that could be default  to Grails (unic action in controller): [#L59](https://github.com/erickmorales3/action-logging/blob/master/grails-app/conf/ActionLoggingFilters.groovy#L59)

Thanks for suggestions
