### ISSUE TITLE
Evaluate session usage

### ISSUE THREAD

**Issue by rpalcolea** [erickmorales3/action-logging#6]
I noticed that you store the `ActionLoggingEvent.groovy` instance in the session in order to retrieve in the `afterView` and update `endTime` and `totalTime`.

I don't know if this could be a potential issue in memory at Tomcat level or if you store the session in a database such as MySQL (https://grails.org/plugin/database-session) or Redis (https://grails.org/plugin/redis-database-session) <- this one serializes the whole Session object in a byte array or JSON.

What do you think about storing the `ActionLoggingEvent` `id` in the session and then retrieve the object from the database in the `afterView`?

**Comment by burtbeckwith** [comment]
I just sent a PR with various minor fixes and cleanup and changed from using the session to using the request. It's very similar with Map-like access but avoids some issues when using sessions, and there's no need to perist any of that data for longer than one request. One big potential issue is thread-safety; if a regular browser request and an async Ajax request happened around the same time, one could easily overwrite the other's data. Another issue is that you scale the web tier and have distributed sessions, you'll keep copies of this data on multiple machines which has a fairly small cost considering the size of the objects, but has zero benefit.

**Comment by rpalcolea** [comment]
That makes sense @burtbeckwith 

Thanks again for your help and commitment with the community.
